services:

  backend:
    image: sledzior/f1/backend
    environment:
      - EXTERNAL_API_URL=http://fastf1_wrapper:8081/wrapper
      - SERVER_PORT=8080
      - JWT_SECRET=${JWT_SECRET:-default_secret_for_development_only}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
      - DATABASE_PATH=/data/f1_data.db
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - f1_db_data:/data

  fastf1_wrapper:
    image: sledzior/f1/fastf1_wrapper
    build:
      context: ./fastf1_wrapper
    ports:
      - "8081:8081"
    volumes:
      - f1_wrapper_cache:/app/.cache

  frontend:
    image: sledzior/f1/frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8080

volumes:
  f1_db_data:
  f1_wrapper_cache:
