export interface SessionResult {
  position: number;
  driver: string;
  team: string;
  time: string;
  gap: string;
}

export interface Session {
  code: string;
  name: string;
  startTime: string;
  results?: SessionResult[];
}

export interface TrackStats {
  length: string;
  corners: number;
  drsZones: number;
  lapRecord: string;
  lapRecordHolder: string;
  lapRecordYear: number;
}

export interface Event {
  id: string;
  title: string;
  country: string;
  countryCode: string;
  location: string;
  trackName: string;
  dateFrom: string;
  dateTo: string;
  sessions: Session[];
  trackStats: TrackStats;
  status: "completed" | "ongoing" | "upcoming";
}

// Helper to get session codes for card display
export function getSessionCodes(sessions: Session[]): string[] {
  return sessions.map((s) => s.code);
}

const sampleResults: SessionResult[] = [
  { position: 1, driver: "M. Verstappen", team: "Red Bull Racing", time: "1:30.123", gap: "-" },
  { position: 2, driver: "L. Norris", team: "McLaren", time: "1:30.456", gap: "+0.333" },
  { position: 3, driver: "C. Leclerc", team: "Ferrari", time: "1:30.678", gap: "+0.555" },
  { position: 4, driver: "O. Piastri", team: "McLaren", time: "1:30.890", gap: "+0.767" },
  { position: 5, driver: "C. Sainz", team: "Ferrari", time: "1:31.012", gap: "+0.889" },
  { position: 6, driver: "L. Hamilton", team: "Ferrari", time: "1:31.234", gap: "+1.111" },
  { position: 7, driver: "G. Russell", team: "Mercedes", time: "1:31.456", gap: "+1.333" },
  { position: 8, driver: "S. Perez", team: "Red Bull Racing", time: "1:31.678", gap: "+1.555" },
  { position: 9, driver: "F. Alonso", team: "Aston Martin", time: "1:31.890", gap: "+1.767" },
  { position: 10, driver: "L. Stroll", team: "Aston Martin", time: "1:32.012", gap: "+1.889" },
];

export const events2026: Event[] = [
  {
    id: "bh-2026",
    title: "Bahrain Grand Prix",
    country: "Bahrain",
    countryCode: "BH",
    location: "Sakhir",
    trackName: "Bahrain International Circuit",
    dateFrom: "28/02",
    dateTo: "02/03",
    status: "upcoming",
    trackStats: {
      length: "5.412 km",
      corners: 15,
      drsZones: 3,
      lapRecord: "1:31.447",
      lapRecordHolder: "P. de la Rosa",
      lapRecordYear: 2005,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "14:30" },
      { code: "P2", name: "Practice 2", startTime: "18:00" },
      { code: "P3", name: "Practice 3", startTime: "15:30" },
      { code: "Q", name: "Qualifying", startTime: "19:00" },
      { code: "R", name: "Race", startTime: "18:00" },
    ],
  },
  {
    id: "sa-2026",
    title: "Saudi Arabian Grand Prix",
    country: "Saudi Arabia",
    countryCode: "SA",
    location: "Jeddah",
    trackName: "Jeddah Corniche Circuit",
    dateFrom: "07/03",
    dateTo: "09/03",
    status: "upcoming",
    trackStats: {
      length: "6.174 km",
      corners: 27,
      drsZones: 3,
      lapRecord: "1:30.734",
      lapRecordHolder: "M. Verstappen",
      lapRecordYear: 2024,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "16:30" },
      { code: "P2", name: "Practice 2", startTime: "20:00" },
      { code: "P3", name: "Practice 3", startTime: "16:30" },
      { code: "Q", name: "Qualifying", startTime: "20:00" },
      { code: "R", name: "Race", startTime: "20:00" },
    ],
  },
  {
    id: "au-2026",
    title: "Australian Grand Prix",
    country: "Australia",
    countryCode: "AU",
    location: "Melbourne",
    trackName: "Albert Park Circuit",
    dateFrom: "21/03",
    dateTo: "23/03",
    status: "upcoming",
    trackStats: {
      length: "5.278 km",
      corners: 14,
      drsZones: 4,
      lapRecord: "1:19.813",
      lapRecordHolder: "C. Leclerc",
      lapRecordYear: 2024,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "12:30" },
      { code: "P2", name: "Practice 2", startTime: "16:00" },
      { code: "P3", name: "Practice 3", startTime: "12:30" },
      { code: "Q", name: "Qualifying", startTime: "16:00" },
      { code: "R", name: "Race", startTime: "15:00" },
    ],
  },
  {
    id: "jp-2026",
    title: "Japanese Grand Prix",
    country: "Japan",
    countryCode: "JP",
    location: "Suzuka",
    trackName: "Suzuka International Racing Course",
    dateFrom: "04/04",
    dateTo: "06/04",
    status: "upcoming",
    trackStats: {
      length: "5.807 km",
      corners: 18,
      drsZones: 2,
      lapRecord: "1:30.983",
      lapRecordHolder: "L. Hamilton",
      lapRecordYear: 2019,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "11:30" },
      { code: "P2", name: "Practice 2", startTime: "15:00" },
      { code: "P3", name: "Practice 3", startTime: "11:30" },
      { code: "Q", name: "Qualifying", startTime: "15:00" },
      { code: "R", name: "Race", startTime: "14:00" },
    ],
  },
  {
    id: "cn-2026",
    title: "Chinese Grand Prix",
    country: "China",
    countryCode: "CN",
    location: "Shanghai",
    trackName: "Shanghai International Circuit",
    dateFrom: "18/04",
    dateTo: "20/04",
    status: "upcoming",
    trackStats: {
      length: "5.451 km",
      corners: 16,
      drsZones: 2,
      lapRecord: "1:32.238",
      lapRecordHolder: "M. Schumacher",
      lapRecordYear: 2004,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "11:30" },
      { code: "SQ", name: "Sprint Qualifying", startTime: "15:30" },
      { code: "S", name: "Sprint", startTime: "11:00" },
      { code: "Q", name: "Qualifying", startTime: "15:00" },
      { code: "R", name: "Race", startTime: "14:00" },
    ],
  },
  {
    id: "us-mia-2026",
    title: "Miami Grand Prix",
    country: "United States",
    countryCode: "US",
    location: "Miami",
    trackName: "Miami International Autodrome",
    dateFrom: "02/05",
    dateTo: "04/05",
    status: "upcoming",
    trackStats: {
      length: "5.412 km",
      corners: 19,
      drsZones: 3,
      lapRecord: "1:29.708",
      lapRecordHolder: "M. Verstappen",
      lapRecordYear: 2023,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "18:30" },
      { code: "SQ", name: "Sprint Qualifying", startTime: "22:30" },
      { code: "S", name: "Sprint", startTime: "18:00" },
      { code: "Q", name: "Qualifying", startTime: "22:00" },
      { code: "R", name: "Race", startTime: "22:00" },
    ],
  },
  {
    id: "it-imola-2026",
    title: "Emilia Romagna Grand Prix",
    country: "Italy",
    countryCode: "IT",
    location: "Imola",
    trackName: "Autodromo Enzo e Dino Ferrari",
    dateFrom: "16/05",
    dateTo: "18/05",
    status: "upcoming",
    trackStats: {
      length: "4.909 km",
      corners: 19,
      drsZones: 2,
      lapRecord: "1:15.484",
      lapRecordHolder: "L. Hamilton",
      lapRecordYear: 2020,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30" },
      { code: "P2", name: "Practice 2", startTime: "17:00" },
      { code: "P3", name: "Practice 3", startTime: "12:30" },
      { code: "Q", name: "Qualifying", startTime: "16:00" },
      { code: "R", name: "Race", startTime: "15:00" },
    ],
  },
  {
    id: "mc-2026",
    title: "Monaco Grand Prix",
    country: "Monaco",
    countryCode: "MC",
    location: "Monte Carlo",
    trackName: "Circuit de Monaco",
    dateFrom: "23/05",
    dateTo: "25/05",
    status: "upcoming",
    trackStats: {
      length: "3.337 km",
      corners: 19,
      drsZones: 1,
      lapRecord: "1:12.909",
      lapRecordHolder: "L. Hamilton",
      lapRecordYear: 2021,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30" },
      { code: "P2", name: "Practice 2", startTime: "17:00" },
      { code: "P3", name: "Practice 3", startTime: "12:30" },
      { code: "Q", name: "Qualifying", startTime: "16:00" },
      { code: "R", name: "Race", startTime: "15:00" },
    ],
  },
  {
    id: "es-2026",
    title: "Spanish Grand Prix",
    country: "Spain",
    countryCode: "ES",
    location: "Barcelona",
    trackName: "Circuit de Barcelona-Catalunya",
    dateFrom: "30/05",
    dateTo: "01/06",
    status: "upcoming",
    trackStats: {
      length: "4.657 km",
      corners: 14,
      drsZones: 2,
      lapRecord: "1:16.330",
      lapRecordHolder: "M. Verstappen",
      lapRecordYear: 2023,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30" },
      { code: "P2", name: "Practice 2", startTime: "17:00" },
      { code: "P3", name: "Practice 3", startTime: "12:30" },
      { code: "Q", name: "Qualifying", startTime: "16:00" },
      { code: "R", name: "Race", startTime: "15:00" },
    ],
  },
  {
    id: "ca-2026",
    title: "Canadian Grand Prix",
    country: "Canada",
    countryCode: "CA",
    location: "Montreal",
    trackName: "Circuit Gilles Villeneuve",
    dateFrom: "13/06",
    dateTo: "15/06",
    status: "upcoming",
    trackStats: {
      length: "4.361 km",
      corners: 14,
      drsZones: 2,
      lapRecord: "1:13.078",
      lapRecordHolder: "V. Bottas",
      lapRecordYear: 2019,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "19:30" },
      { code: "P2", name: "Practice 2", startTime: "23:00" },
      { code: "P3", name: "Practice 3", startTime: "18:30" },
      { code: "Q", name: "Qualifying", startTime: "22:00" },
      { code: "R", name: "Race", startTime: "20:00" },
    ],
  },
  {
    id: "at-2026",
    title: "Austrian Grand Prix",
    country: "Austria",
    countryCode: "AT",
    location: "Spielberg",
    trackName: "Red Bull Ring",
    dateFrom: "27/06",
    dateTo: "29/06",
    status: "upcoming",
    trackStats: {
      length: "4.318 km",
      corners: 10,
      drsZones: 3,
      lapRecord: "1:05.619",
      lapRecordHolder: "C. Sainz",
      lapRecordYear: 2020,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "12:30" },
      { code: "SQ", name: "Sprint Qualifying", startTime: "16:30" },
      { code: "S", name: "Sprint", startTime: "12:00" },
      { code: "Q", name: "Qualifying", startTime: "16:00" },
      { code: "R", name: "Race", startTime: "15:00" },
    ],
  },
  {
    id: "gb-2026",
    title: "British Grand Prix",
    country: "United Kingdom",
    countryCode: "GB",
    location: "Silverstone",
    trackName: "Silverstone Circuit",
    dateFrom: "04/07",
    dateTo: "06/07",
    status: "upcoming",
    trackStats: {
      length: "5.891 km",
      corners: 18,
      drsZones: 2,
      lapRecord: "1:27.097",
      lapRecordHolder: "M. Verstappen",
      lapRecordYear: 2020,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30" },
      { code: "P2", name: "Practice 2", startTime: "17:00" },
      { code: "P3", name: "Practice 3", startTime: "12:30" },
      { code: "Q", name: "Qualifying", startTime: "16:00" },
      { code: "R", name: "Race", startTime: "16:00" },
    ],
  },
  {
    id: "be-2026",
    title: "Belgian Grand Prix",
    country: "Belgium",
    countryCode: "BE",
    location: "Spa-Francorchamps",
    trackName: "Circuit de Spa-Francorchamps",
    dateFrom: "25/07",
    dateTo: "27/07",
    status: "upcoming",
    trackStats: {
      length: "7.004 km",
      corners: 19,
      drsZones: 2,
      lapRecord: "1:46.286",
      lapRecordHolder: "V. Bottas",
      lapRecordYear: 2018,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30" },
      { code: "SQ", name: "Sprint Qualifying", startTime: "17:30" },
      { code: "S", name: "Sprint", startTime: "12:00" },
      { code: "Q", name: "Qualifying", startTime: "16:00" },
      { code: "R", name: "Race", startTime: "15:00" },
    ],
  },
  {
    id: "hu-2026",
    title: "Hungarian Grand Prix",
    country: "Hungary",
    countryCode: "HU",
    location: "Budapest",
    trackName: "Hungaroring",
    dateFrom: "01/08",
    dateTo: "03/08",
    status: "upcoming",
    trackStats: {
      length: "4.381 km",
      corners: 14,
      drsZones: 2,
      lapRecord: "1:16.627",
      lapRecordHolder: "L. Hamilton",
      lapRecordYear: 2020,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30" },
      { code: "P2", name: "Practice 2", startTime: "17:00" },
      { code: "P3", name: "Practice 3", startTime: "12:30" },
      { code: "Q", name: "Qualifying", startTime: "16:00" },
      { code: "R", name: "Race", startTime: "15:00" },
    ],
  },
  {
    id: "nl-2026",
    title: "Dutch Grand Prix",
    country: "Netherlands",
    countryCode: "NL",
    location: "Zandvoort",
    trackName: "Circuit Zandvoort",
    dateFrom: "29/08",
    dateTo: "31/08",
    status: "upcoming",
    trackStats: {
      length: "4.259 km",
      corners: 14,
      drsZones: 2,
      lapRecord: "1:11.097",
      lapRecordHolder: "L. Norris",
      lapRecordYear: 2024,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "12:30" },
      { code: "P2", name: "Practice 2", startTime: "16:00" },
      { code: "P3", name: "Practice 3", startTime: "11:30" },
      { code: "Q", name: "Qualifying", startTime: "15:00" },
      { code: "R", name: "Race", startTime: "15:00" },
    ],
  },
  {
    id: "it-monza-2026",
    title: "Italian Grand Prix",
    country: "Italy",
    countryCode: "IT",
    location: "Monza",
    trackName: "Autodromo Nazionale Monza",
    dateFrom: "05/09",
    dateTo: "07/09",
    status: "upcoming",
    trackStats: {
      length: "5.793 km",
      corners: 11,
      drsZones: 2,
      lapRecord: "1:21.046",
      lapRecordHolder: "R. Barrichello",
      lapRecordYear: 2004,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30" },
      { code: "P2", name: "Practice 2", startTime: "17:00" },
      { code: "P3", name: "Practice 3", startTime: "12:30" },
      { code: "Q", name: "Qualifying", startTime: "16:00" },
      { code: "R", name: "Race", startTime: "15:00" },
    ],
  },
  {
    id: "az-2026",
    title: "Azerbaijan Grand Prix",
    country: "Azerbaijan",
    countryCode: "AZ",
    location: "Baku",
    trackName: "Baku City Circuit",
    dateFrom: "19/09",
    dateTo: "21/09",
    status: "upcoming",
    trackStats: {
      length: "6.003 km",
      corners: 20,
      drsZones: 2,
      lapRecord: "1:43.009",
      lapRecordHolder: "C. Leclerc",
      lapRecordYear: 2019,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30" },
      { code: "P2", name: "Practice 2", startTime: "17:00" },
      { code: "P3", name: "Practice 3", startTime: "12:30" },
      { code: "Q", name: "Qualifying", startTime: "16:00" },
      { code: "R", name: "Race", startTime: "15:00" },
    ],
  },
  {
    id: "sg-2026",
    title: "Singapore Grand Prix",
    country: "Singapore",
    countryCode: "SG",
    location: "Marina Bay",
    trackName: "Marina Bay Street Circuit",
    dateFrom: "03/10",
    dateTo: "05/10",
    status: "upcoming",
    trackStats: {
      length: "4.940 km",
      corners: 19,
      drsZones: 3,
      lapRecord: "1:35.867",
      lapRecordHolder: "L. Hamilton",
      lapRecordYear: 2023,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "17:30" },
      { code: "P2", name: "Practice 2", startTime: "21:00" },
      { code: "P3", name: "Practice 3", startTime: "17:30" },
      { code: "Q", name: "Qualifying", startTime: "21:00" },
      { code: "R", name: "Race", startTime: "20:00" },
    ],
  },
  {
    id: "us-austin-2026",
    title: "United States Grand Prix",
    country: "United States",
    countryCode: "US",
    location: "Austin",
    trackName: "Circuit of the Americas",
    dateFrom: "17/10",
    dateTo: "19/10",
    status: "upcoming",
    trackStats: {
      length: "5.513 km",
      corners: 20,
      drsZones: 2,
      lapRecord: "1:36.169",
      lapRecordHolder: "C. Leclerc",
      lapRecordYear: 2019,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "19:30" },
      { code: "SQ", name: "Sprint Qualifying", startTime: "23:30" },
      { code: "S", name: "Sprint", startTime: "20:00" },
      { code: "Q", name: "Qualifying", startTime: "00:00" },
      { code: "R", name: "Race", startTime: "21:00" },
    ],
  },
  {
    id: "mx-2026",
    title: "Mexico City Grand Prix",
    country: "Mexico",
    countryCode: "MX",
    location: "Mexico City",
    trackName: "Autódromo Hermanos Rodríguez",
    dateFrom: "24/10",
    dateTo: "26/10",
    status: "upcoming",
    trackStats: {
      length: "4.304 km",
      corners: 17,
      drsZones: 3,
      lapRecord: "1:17.774",
      lapRecordHolder: "V. Bottas",
      lapRecordYear: 2021,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "20:30" },
      { code: "P2", name: "Practice 2", startTime: "00:00" },
      { code: "P3", name: "Practice 3", startTime: "19:30" },
      { code: "Q", name: "Qualifying", startTime: "23:00" },
      { code: "R", name: "Race", startTime: "21:00" },
    ],
  },
  {
    id: "br-2026",
    title: "São Paulo Grand Prix",
    country: "Brazil",
    countryCode: "BR",
    location: "São Paulo",
    trackName: "Autódromo José Carlos Pace",
    dateFrom: "07/11",
    dateTo: "09/11",
    status: "upcoming",
    trackStats: {
      length: "4.309 km",
      corners: 15,
      drsZones: 2,
      lapRecord: "1:10.540",
      lapRecordHolder: "V. Bottas",
      lapRecordYear: 2018,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "15:30" },
      { code: "SQ", name: "Sprint Qualifying", startTime: "19:30" },
      { code: "S", name: "Sprint", startTime: "15:00" },
      { code: "Q", name: "Qualifying", startTime: "19:00" },
      { code: "R", name: "Race", startTime: "18:00" },
    ],
  },
  {
    id: "us-vegas-2026",
    title: "Las Vegas Grand Prix",
    country: "United States",
    countryCode: "US",
    location: "Las Vegas",
    trackName: "Las Vegas Strip Circuit",
    dateFrom: "20/11",
    dateTo: "22/11",
    status: "upcoming",
    trackStats: {
      length: "6.201 km",
      corners: 17,
      drsZones: 2,
      lapRecord: "1:35.490",
      lapRecordHolder: "O. Piastri",
      lapRecordYear: 2024,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "04:30" },
      { code: "P2", name: "Practice 2", startTime: "08:00" },
      { code: "P3", name: "Practice 3", startTime: "04:30" },
      { code: "Q", name: "Qualifying", startTime: "08:00" },
      { code: "R", name: "Race", startTime: "07:00" },
    ],
  },
  {
    id: "qa-2026",
    title: "Qatar Grand Prix",
    country: "Qatar",
    countryCode: "QA",
    location: "Lusail",
    trackName: "Lusail International Circuit",
    dateFrom: "28/11",
    dateTo: "30/11",
    status: "upcoming",
    trackStats: {
      length: "5.419 km",
      corners: 16,
      drsZones: 2,
      lapRecord: "1:24.319",
      lapRecordHolder: "M. Verstappen",
      lapRecordYear: 2023,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "15:30" },
      { code: "SQ", name: "Sprint Qualifying", startTime: "19:30" },
      { code: "S", name: "Sprint", startTime: "16:00" },
      { code: "Q", name: "Qualifying", startTime: "20:00" },
      { code: "R", name: "Race", startTime: "19:00" },
    ],
  },
  {
    id: "ae-2026",
    title: "Abu Dhabi Grand Prix",
    country: "United Arab Emirates",
    countryCode: "AE",
    location: "Abu Dhabi",
    trackName: "Yas Marina Circuit",
    dateFrom: "05/12",
    dateTo: "07/12",
    status: "upcoming",
    trackStats: {
      length: "5.281 km",
      corners: 16,
      drsZones: 2,
      lapRecord: "1:26.103",
      lapRecordHolder: "M. Verstappen",
      lapRecordYear: 2021,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30" },
      { code: "P2", name: "Practice 2", startTime: "17:00" },
      { code: "P3", name: "Practice 3", startTime: "14:30" },
      { code: "Q", name: "Qualifying", startTime: "18:00" },
      { code: "R", name: "Race", startTime: "17:00" },
    ],
  },
];

export const events2025: Event[] = [
  {
    id: "au-2025",
    title: "Australian Grand Prix",
    country: "Australia",
    countryCode: "AU",
    location: "Melbourne",
    trackName: "Albert Park Circuit",
    dateFrom: "14/03",
    dateTo: "16/03",
    status: "completed",
    trackStats: {
      length: "5.278 km",
      corners: 14,
      drsZones: 4,
      lapRecord: "1:19.813",
      lapRecordHolder: "C. Leclerc",
      lapRecordYear: 2024,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "12:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "16:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "12:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "16:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "15:00", results: sampleResults },
    ],
  },
  {
    id: "cn-2025",
    title: "Chinese Grand Prix",
    country: "China",
    countryCode: "CN",
    location: "Shanghai",
    trackName: "Shanghai International Circuit",
    dateFrom: "21/03",
    dateTo: "23/03",
    status: "completed",
    trackStats: {
      length: "5.451 km",
      corners: 16,
      drsZones: 2,
      lapRecord: "1:32.238",
      lapRecordHolder: "M. Schumacher",
      lapRecordYear: 2004,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "11:30", results: sampleResults },
      { code: "SQ", name: "Sprint Qualifying", startTime: "15:30", results: sampleResults },
      { code: "S", name: "Sprint", startTime: "11:00", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "15:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "14:00", results: sampleResults },
    ],
  },
  {
    id: "jp-2025",
    title: "Japanese Grand Prix",
    country: "Japan",
    countryCode: "JP",
    location: "Suzuka",
    trackName: "Suzuka International Racing Course",
    dateFrom: "04/04",
    dateTo: "06/04",
    status: "completed",
    trackStats: {
      length: "5.807 km",
      corners: 18,
      drsZones: 2,
      lapRecord: "1:30.983",
      lapRecordHolder: "L. Hamilton",
      lapRecordYear: 2019,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "11:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "15:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "11:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "15:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "14:00", results: sampleResults },
    ],
  },
  {
    id: "bh-2025",
    title: "Bahrain Grand Prix",
    country: "Bahrain",
    countryCode: "BH",
    location: "Sakhir",
    trackName: "Bahrain International Circuit",
    dateFrom: "11/04",
    dateTo: "13/04",
    status: "completed",
    trackStats: {
      length: "5.412 km",
      corners: 15,
      drsZones: 3,
      lapRecord: "1:31.447",
      lapRecordHolder: "P. de la Rosa",
      lapRecordYear: 2005,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "14:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "18:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "15:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "19:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "18:00", results: sampleResults },
    ],
  },
  {
    id: "sa-2025",
    title: "Saudi Arabian Grand Prix",
    country: "Saudi Arabia",
    countryCode: "SA",
    location: "Jeddah",
    trackName: "Jeddah Corniche Circuit",
    dateFrom: "18/04",
    dateTo: "20/04",
    status: "completed",
    trackStats: {
      length: "6.174 km",
      corners: 27,
      drsZones: 3,
      lapRecord: "1:30.734",
      lapRecordHolder: "M. Verstappen",
      lapRecordYear: 2024,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "16:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "20:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "16:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "20:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "20:00", results: sampleResults },
    ],
  },
  {
    id: "us-mia-2025",
    title: "Miami Grand Prix",
    country: "United States",
    countryCode: "US",
    location: "Miami",
    trackName: "Miami International Autodrome",
    dateFrom: "02/05",
    dateTo: "04/05",
    status: "completed",
    trackStats: {
      length: "5.412 km",
      corners: 19,
      drsZones: 3,
      lapRecord: "1:29.708",
      lapRecordHolder: "M. Verstappen",
      lapRecordYear: 2023,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "18:30", results: sampleResults },
      { code: "SQ", name: "Sprint Qualifying", startTime: "22:30", results: sampleResults },
      { code: "S", name: "Sprint", startTime: "18:00", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "22:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "22:00", results: sampleResults },
    ],
  },
  {
    id: "it-imola-2025",
    title: "Emilia Romagna Grand Prix",
    country: "Italy",
    countryCode: "IT",
    location: "Imola",
    trackName: "Autodromo Enzo e Dino Ferrari",
    dateFrom: "16/05",
    dateTo: "18/05",
    status: "completed",
    trackStats: {
      length: "4.909 km",
      corners: 19,
      drsZones: 2,
      lapRecord: "1:15.484",
      lapRecordHolder: "L. Hamilton",
      lapRecordYear: 2020,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "17:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "12:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "16:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "15:00", results: sampleResults },
    ],
  },
  {
    id: "mc-2025",
    title: "Monaco Grand Prix",
    country: "Monaco",
    countryCode: "MC",
    location: "Monte Carlo",
    trackName: "Circuit de Monaco",
    dateFrom: "23/05",
    dateTo: "25/05",
    status: "completed",
    trackStats: {
      length: "3.337 km",
      corners: 19,
      drsZones: 1,
      lapRecord: "1:12.909",
      lapRecordHolder: "L. Hamilton",
      lapRecordYear: 2021,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "17:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "12:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "16:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "15:00", results: sampleResults },
    ],
  },
  {
    id: "es-2025",
    title: "Spanish Grand Prix",
    country: "Spain",
    countryCode: "ES",
    location: "Barcelona",
    trackName: "Circuit de Barcelona-Catalunya",
    dateFrom: "30/05",
    dateTo: "01/06",
    status: "completed",
    trackStats: {
      length: "4.657 km",
      corners: 14,
      drsZones: 2,
      lapRecord: "1:16.330",
      lapRecordHolder: "M. Verstappen",
      lapRecordYear: 2023,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "17:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "12:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "16:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "15:00", results: sampleResults },
    ],
  },
  {
    id: "ca-2025",
    title: "Canadian Grand Prix",
    country: "Canada",
    countryCode: "CA",
    location: "Montreal",
    trackName: "Circuit Gilles Villeneuve",
    dateFrom: "13/06",
    dateTo: "15/06",
    status: "completed",
    trackStats: {
      length: "4.361 km",
      corners: 14,
      drsZones: 2,
      lapRecord: "1:13.078",
      lapRecordHolder: "V. Bottas",
      lapRecordYear: 2019,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "19:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "23:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "18:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "22:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "20:00", results: sampleResults },
    ],
  },
  {
    id: "at-2025",
    title: "Austrian Grand Prix",
    country: "Austria",
    countryCode: "AT",
    location: "Spielberg",
    trackName: "Red Bull Ring",
    dateFrom: "27/06",
    dateTo: "29/06",
    status: "completed",
    trackStats: {
      length: "4.318 km",
      corners: 10,
      drsZones: 3,
      lapRecord: "1:05.619",
      lapRecordHolder: "C. Sainz",
      lapRecordYear: 2020,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "12:30", results: sampleResults },
      { code: "SQ", name: "Sprint Qualifying", startTime: "16:30", results: sampleResults },
      { code: "S", name: "Sprint", startTime: "12:00", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "16:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "15:00", results: sampleResults },
    ],
  },
  {
    id: "gb-2025",
    title: "British Grand Prix",
    country: "United Kingdom",
    countryCode: "GB",
    location: "Silverstone",
    trackName: "Silverstone Circuit",
    dateFrom: "04/07",
    dateTo: "06/07",
    status: "completed",
    trackStats: {
      length: "5.891 km",
      corners: 18,
      drsZones: 2,
      lapRecord: "1:27.097",
      lapRecordHolder: "M. Verstappen",
      lapRecordYear: 2020,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "17:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "12:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "16:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "16:00", results: sampleResults },
    ],
  },
  {
    id: "be-2025",
    title: "Belgian Grand Prix",
    country: "Belgium",
    countryCode: "BE",
    location: "Spa-Francorchamps",
    trackName: "Circuit de Spa-Francorchamps",
    dateFrom: "25/07",
    dateTo: "27/07",
    status: "completed",
    trackStats: {
      length: "7.004 km",
      corners: 19,
      drsZones: 2,
      lapRecord: "1:46.286",
      lapRecordHolder: "V. Bottas",
      lapRecordYear: 2018,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "17:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "12:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "16:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "15:00", results: sampleResults },
    ],
  },
  {
    id: "hu-2025",
    title: "Hungarian Grand Prix",
    country: "Hungary",
    countryCode: "HU",
    location: "Budapest",
    trackName: "Hungaroring",
    dateFrom: "01/08",
    dateTo: "03/08",
    status: "completed",
    trackStats: {
      length: "4.381 km",
      corners: 14,
      drsZones: 2,
      lapRecord: "1:16.627",
      lapRecordHolder: "L. Hamilton",
      lapRecordYear: 2020,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "17:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "12:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "16:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "15:00", results: sampleResults },
    ],
  },
  {
    id: "nl-2025",
    title: "Dutch Grand Prix",
    country: "Netherlands",
    countryCode: "NL",
    location: "Zandvoort",
    trackName: "Circuit Zandvoort",
    dateFrom: "29/08",
    dateTo: "31/08",
    status: "completed",
    trackStats: {
      length: "4.259 km",
      corners: 14,
      drsZones: 2,
      lapRecord: "1:11.097",
      lapRecordHolder: "L. Norris",
      lapRecordYear: 2024,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "12:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "16:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "11:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "15:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "15:00", results: sampleResults },
    ],
  },
  {
    id: "it-monza-2025",
    title: "Italian Grand Prix",
    country: "Italy",
    countryCode: "IT",
    location: "Monza",
    trackName: "Autodromo Nazionale Monza",
    dateFrom: "05/09",
    dateTo: "07/09",
    status: "completed",
    trackStats: {
      length: "5.793 km",
      corners: 11,
      drsZones: 2,
      lapRecord: "1:21.046",
      lapRecordHolder: "R. Barrichello",
      lapRecordYear: 2004,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "17:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "12:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "16:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "15:00", results: sampleResults },
    ],
  },
  {
    id: "az-2025",
    title: "Azerbaijan Grand Prix",
    country: "Azerbaijan",
    countryCode: "AZ",
    location: "Baku",
    trackName: "Baku City Circuit",
    dateFrom: "19/09",
    dateTo: "21/09",
    status: "completed",
    trackStats: {
      length: "6.003 km",
      corners: 20,
      drsZones: 2,
      lapRecord: "1:43.009",
      lapRecordHolder: "C. Leclerc",
      lapRecordYear: 2019,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "17:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "12:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "16:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "15:00", results: sampleResults },
    ],
  },
  {
    id: "sg-2025",
    title: "Singapore Grand Prix",
    country: "Singapore",
    countryCode: "SG",
    location: "Marina Bay",
    trackName: "Marina Bay Street Circuit",
    dateFrom: "03/10",
    dateTo: "05/10",
    status: "completed",
    trackStats: {
      length: "4.940 km",
      corners: 19,
      drsZones: 3,
      lapRecord: "1:35.867",
      lapRecordHolder: "L. Hamilton",
      lapRecordYear: 2023,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "17:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "21:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "17:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "21:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "20:00", results: sampleResults },
    ],
  },
  {
    id: "us-austin-2025",
    title: "United States Grand Prix",
    country: "United States",
    countryCode: "US",
    location: "Austin",
    trackName: "Circuit of the Americas",
    dateFrom: "17/10",
    dateTo: "19/10",
    status: "completed",
    trackStats: {
      length: "5.513 km",
      corners: 20,
      drsZones: 2,
      lapRecord: "1:36.169",
      lapRecordHolder: "C. Leclerc",
      lapRecordYear: 2019,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "19:30", results: sampleResults },
      { code: "SQ", name: "Sprint Qualifying", startTime: "23:30", results: sampleResults },
      { code: "S", name: "Sprint", startTime: "20:00", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "00:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "21:00", results: sampleResults },
    ],
  },
  {
    id: "mx-2025",
    title: "Mexico City Grand Prix",
    country: "Mexico",
    countryCode: "MX",
    location: "Mexico City",
    trackName: "Autódromo Hermanos Rodríguez",
    dateFrom: "24/10",
    dateTo: "26/10",
    status: "completed",
    trackStats: {
      length: "4.304 km",
      corners: 17,
      drsZones: 3,
      lapRecord: "1:17.774",
      lapRecordHolder: "V. Bottas",
      lapRecordYear: 2021,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "20:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "00:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "19:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "23:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "21:00", results: sampleResults },
    ],
  },
  {
    id: "br-2025",
    title: "São Paulo Grand Prix",
    country: "Brazil",
    countryCode: "BR",
    location: "São Paulo",
    trackName: "Autódromo José Carlos Pace",
    dateFrom: "07/11",
    dateTo: "09/11",
    status: "completed",
    trackStats: {
      length: "4.309 km",
      corners: 15,
      drsZones: 2,
      lapRecord: "1:10.540",
      lapRecordHolder: "V. Bottas",
      lapRecordYear: 2018,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "15:30", results: sampleResults },
      { code: "SQ", name: "Sprint Qualifying", startTime: "19:30", results: sampleResults },
      { code: "S", name: "Sprint", startTime: "15:00", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "19:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "18:00", results: sampleResults },
    ],
  },
  {
    id: "us-vegas-2025",
    title: "Las Vegas Grand Prix",
    country: "United States",
    countryCode: "US",
    location: "Las Vegas",
    trackName: "Las Vegas Strip Circuit",
    dateFrom: "20/11",
    dateTo: "22/11",
    status: "completed",
    trackStats: {
      length: "6.201 km",
      corners: 17,
      drsZones: 2,
      lapRecord: "1:35.490",
      lapRecordHolder: "O. Piastri",
      lapRecordYear: 2024,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "04:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "08:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "04:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "08:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "07:00", results: sampleResults },
    ],
  },
  {
    id: "qa-2025",
    title: "Qatar Grand Prix",
    country: "Qatar",
    countryCode: "QA",
    location: "Lusail",
    trackName: "Lusail International Circuit",
    dateFrom: "28/11",
    dateTo: "30/11",
    status: "completed",
    trackStats: {
      length: "5.419 km",
      corners: 16,
      drsZones: 2,
      lapRecord: "1:24.319",
      lapRecordHolder: "M. Verstappen",
      lapRecordYear: 2023,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "15:30", results: sampleResults },
      { code: "SQ", name: "Sprint Qualifying", startTime: "19:30", results: sampleResults },
      { code: "S", name: "Sprint", startTime: "16:00", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "20:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "19:00", results: sampleResults },
    ],
  },
  {
    id: "ae-2025",
    title: "Abu Dhabi Grand Prix",
    country: "United Arab Emirates",
    countryCode: "AE",
    location: "Abu Dhabi",
    trackName: "Yas Marina Circuit",
    dateFrom: "05/12",
    dateTo: "07/12",
    status: "completed",
    trackStats: {
      length: "5.281 km",
      corners: 16,
      drsZones: 2,
      lapRecord: "1:26.103",
      lapRecordHolder: "M. Verstappen",
      lapRecordYear: 2021,
    },
    sessions: [
      { code: "P1", name: "Practice 1", startTime: "13:30", results: sampleResults },
      { code: "P2", name: "Practice 2", startTime: "17:00", results: sampleResults },
      { code: "P3", name: "Practice 3", startTime: "14:30", results: sampleResults },
      { code: "Q", name: "Qualifying", startTime: "18:00", results: sampleResults },
      { code: "R", name: "Race", startTime: "17:00", results: sampleResults },
    ],
  },
];

export function getEventsByYear(year: number): Event[] {
  switch (year) {
    case 2026:
      return events2026;
    case 2025:
      return events2025;
    default:
      return events2026;
  }
}

export function getEventById(id: string, year: number): Event | undefined {
  const events = getEventsByYear(year);
  return events.find((event) => event.id === id);
}
